[project]
name = "slaw"
version = "1.0.0"
description = "Dev environment requirements for SLAW labs"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pre-commit==4.2.0", # run `pre-commit install` to install the hooks prior to committing
    "boto3==1.37.19",
]
